---
sudo: required
os: osx

before_install:
  - brew update
  - brew outdated docker || brew upgrade docker
  - brew outdated docker-machine || brew upgrade docker-machine
  - brew outdated docker-compose || brew upgrade docker-compose
  - /usr/local/bin/docker-machine create dev

install:
  - sudo easy_install pip
  - sudo bash ./docker_machine_mount_nfs.sh

script:
  - sudo bash ./test.sh
