---
sudo: required
os: osx

before_install:
  - brew update
  - brew install docker
  - brew install docker-machine
  - brew install docker-compose
  - /usr/local/bin/docker-machine create dev

install:
  - sudo easy_install pip
  - sudo bash ./docker_machine_mount_nfs.sh

script:
  - sudo bash ./test.sh
